name: GoBalance Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
      - name: Build
        run: make build
      - name: Upload Builds
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            ./deploy_scripts/assets/app_server.zip
            ./deploy_scripts/assets/load_balancer.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Download Builds
        uses: actions/download-artifact@v3
        with:
          name: builds
          path: ./deploy_scripts/assets

      - name: CDK Deploy
        env:
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
        run: make deploy
